### ISSUE TITLE
Bugs in BJTU-M502075B-2023

### ISSUE THREAD

**Issue by ghost** [nipirennipi/BJTU-M502075B-2023#2]
In the **Python3.11** environment, I encountered the following bugs:

In **utils.py**, line 60: 
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 1389: illegal multibyte sequence.

In **dataset.py**, line 82: 
TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).

**Comment by ghost** [comment]
> In the **Python3.11** environment, I encountered the following bugs:
> 
> In **utils.py**, line 60: UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 1389: illegal multibyte sequence.
> 
> In **dataset.py**, line 82: TypeError: Population must be a sequence. For dicts or sets, use sorted(d).

In **utils.py**, line 60:
`with open(vectors_path, 'r') as f:`
need to be changed to:
`with open(vectors_path, encoding='utf-8', mode='r') as f:`

In **dataset.py**, line 82: 
`val_imps = random.sample(self.impid2idx.keys(), val_imps_len)`
need to be changed to:
`val_imps = random.sample(list(self.impid2idx), val_imps_len)`

**Comment by nipirennipi** [comment]
The code works fine in python3.8, and there may be some changes to the code in your runtime environment.
