### ISSUE TITLE
The problem of package NLTK

### ISSUE THREAD

**Issue by ghost** [nipirennipi/BJTU-M502075B-2023#3]
There was a problem running the shell script run.sh

![image](https://github.com/nipirennipi/BJTU-M502075B-2023/assets/94963461/be510a65-c070-422c-8dc5-321337404c86)

**Comment by nipirennipi** [comment]
solution: [使用nltk时，报错Resource punkt not found - 知乎](https://zhuanlan.zhihu.com/p/433423216)

**Comment by ghost** [comment]
> There was a problem running the shell script run.sh
> 
> ![image](https://user-images.githubusercontent.com/94963461/277575549-be510a65-c070-422c-8dc5-321337404c86.png)

Add the following file to any path in the diagram.
[nltk_data.zip](https://github.com/nipirennipi/BJTU-M502075B-2023/files/13111713/nltk_data.zip)

Note that the path must meet the following requirements:
Take the second path in the diagram as an example: D:\Python\nltk_data\tokenizers\punkt.
